import type { GameCase } from "./types";

/**
 * Case 02 — The Nova-Tech File (Asteron Consumer Electronics, Pune).
 * A procurement-fraud dossier: approved POs quietly inflated, invoices matched
 * to the inflated numbers, and an audit trail that names the one employee who
 * touched every revision. Solution: Sahil Mehta · Nova-Tech Components ·
 * ₹9.3 lakh inflated value → Impact band B.
 */
export const NOVATECH: GameCase = {
  id: "nova-tech",
  caseNo: "FC-07/NV-26",
  title: "The Nova-Tech File",
  company: "Asteron Consumer Electronics Pvt. Ltd.",
  industry: "Consumer Electronics Manufacturing",
  place: "Pune, Maharashtra",
  period: "April 2025 – March 2026",
  difficulty: "Moderate",
  minutes: 40,
  accusationPrompt: "Which employee drove the inflated orders?",
  methodPlaceholder:
    "Describe the scheme — which POs were revised, by whom, how the vendor coordinated it, and the money that moved…",
  footnote:
    "A fictional training case. Companies, vendors and individuals are fictitious; any resemblance is coincidental.",
  narrative: [
    "Asteron Consumer Electronics builds the small electronics India assembles into everything else. In FY 2025–26 its procurement spend jumped from ₹119.8 crore to ₹143.9 crore. Revenue rose too — but not by enough to explain it.",
    "The company's own controls say it all: purchases above ₹5 lakh need extra approval, above ₹25 lakh need the CFO, every PO change must be documented, and supplier bank details need independent verification. Someone inside knew these rules intimately — because the paperwork that breaks them is flawless.",
    "Internal audit has flagged transactions and procurement records for review. Four established vendors, six employees with clearance, forty logged payments, and a purchase-order trail with two revisions nobody can properly explain.",
    "Examine the file. Connect the records — a single document never convicts anyone. Then name the employee, the vendor, the outside contact, and the money.",
  ],
  suspects: [
    {
      id: "arjun-rao",
      name: "Arjun Rao",
      role: "Chief Financial Officer",
      location: "Pune — HQ",
      age: 51,
      motive:
        "Signs every high-value approval, including PO-2571 at ₹37,00,000. If spending controls failed, they failed on his signature.",
      tell: "Co-approved the original Nova-Tech PO but was never shown the revision that doubled its value. His exposure is oversight, not orchestration.",
      transcript: [
        {
          q: "Mr. Rao, PO-2571 was approved at ₹37 lakh. The final invoice was ₹44.4 lakh. Who approved the increase?",
          a: "Not me. My approval covered the original procurement requirement — 2,000 connector modules. The revised approval came through the procurement office the next day. I sign a dozen of these a week; the system shows the head of procurement cleared it.",
        },
        {
          q: "Procurement rules say anything above ₹25 lakh needs your sign-off. ₹44.4 lakh is above ₹25 lakh.",
          a: "And if that revised file had reached my desk, I would have asked why a ₹7.4 lakh quantity change landed one day after approval. It didn't reach my desk. That's precisely the question you should be asking — whose job was it to bring it to me?",
        },
        {
          q: "The CFO approves payments. TX-015 for ₹37 lakh cleared on 18 September.",
          a: "TX-015 matched the approved PO value exactly. What I never saw was TX-017 — a ₹7.4 lakh 'electronic components' payment booked as routine eleven days later. Routine payments don't route to the CFO. That is the gap someone used.",
        },
      ],
    },
    {
      id: "meera-kapoor",
      name: "Meera Kapoor",
      role: "Head of Procurement",
      location: "Pune — HQ",
      age: 46,
      motive:
        "Approved the revised PO-2571 the same afternoon it was changed — on her subordinate's word alone. Her authorization is on every inflated document.",
      tell: "The revision trail runs through her desk, but the changes themselves were keyed by SM029 — Sahil Mehta. She approved what she was shown, and she was shown exactly what he edited.",
      transcript: [
        {
          q: "Ms. Kapoor, you approved revised PO-2571 on 16 September at 14:36. The original was approved the day before.",
          a: "Sahil brought it to me directly — vendor-confirmed additional requirement, production schedule slippage, the usual. He had the revised quantity sheet attached. Twenty-four hundred units against the vendor's own confirmation. I approved within process.",
        },
        {
          q: "Did you verify the additional requirement with the vendor independently?",
          a: "The vendor's confirmation was the attachment. That is how revisions work — the procurement executive manages supplier communication, I authorize. I have six vendor lines and forty POs a quarter. The system trusts the person who maintains the file.",
        },
        {
          q: "A ₹7.4 lakh change, approved in three hours, with no CFO routing. Does that feel right now?",
          a: "(pause) The rulebook says any change to an approved PO must be documented and approved. It was — by me. What the rulebook doesn't say is who checks the document before it reaches me. Apparently, nobody. Now I know why that rule exists.",
        },
      ],
    },
    {
      id: "vikram-joshi",
      name: "Vikram Joshi",
      role: "Accounts Payable Manager",
      location: "Pune — HQ",
      age: 39,
      motive:
        "He flagged the first mismatch in writing — COM-05 — then paid anyway once told the approval was 'in the system'. Both excess payments cleared through his queue.",
      tell: "The person who noticed and the person who was managed. His 17 September query to Sahil Mehta is the moment the paper trail starts defending itself.",
      transcript: [
        {
          q: "Mr. Joshi, on 17 September you wrote: 'The invoice amount is higher than the original PO value.' What happened next?",
          a: "I held it. You can't match INV-NT-1048 against PO-2571 — the totals don't agree. Sahil came back the same day: quantity revised, updated approval in the system. I checked, the revised PO was there, approved. So I released payment per the revised document.",
        },
        {
          q: "Did anyone verify the revised approval against the original purchase requirement?",
          a: "AP matches invoice to PO. That's the control I own. Verifying whether the revision itself was legitimate — whether 400 extra modules were actually needed — that's a procurement and finance question, not mine.",
        },
        {
          q: "In February, Neha Sharma told you to hold TX-030 until the revised approval was visible. You processed it a day later.",
          a: "The approval appeared. That's what I was waiting for. (pause) Look — if the revised approvals themselves were the fraud, then the control I'm standing on is made of paper. Every number I paid matched a document. The documents were the problem.",
        },
      ],
    },
    {
      id: "sahil-mehta",
      name: "Sahil Mehta",
      role: "Procurement Executive",
      location: "Pune — HQ",
      age: 29,
      motive:
        "The only employee who created the POs, revised the quantities, uploaded the vendor's invoices, and told AP the approvals were 'in the system'. Every system change in the audit log traces to SM029 — his user ID.",
      tell: "He held the entire cycle in his hands: requirement → PO → revision → invoice upload → payment clearance. And on both inflated orders, the vendor's quantity sheet came straight to him from Karan Bhatia — never through Meera or the requirements desk.",
      transcript: [
        {
          q: "Mr. Mehta, audit log AL-004: 16 September, 11:07, SM029 changed PO-2571 quantity from 2,000 to 2,400. That's you.",
          a: "Yes. Nova-Tech confirmed additional requirement and I updated the order. That's my job — I create and maintain the POs. The revision was submitted, approved by Ms. Kapoor, documented. Textbook.",
        },
        {
          q: "The 'vendor confirmation' was an email from Karan Bhatia directly to you — COM-02, COM-04. Not to you and Ms. Kapoor. Not to operations.",
          a: "Karan is my day-to-day contact at the vendor. Requirement sheets go to whoever runs the line. That's normal supplier management.",
        },
        {
          q: "You also uploaded their invoice — AL-007 — and told Vikram Joshi the revised approval was 'available in the system' before the balance payment. Then in February the identical pattern repeats on PO-2720, again keyed by you.",
          a: "..... (the recording continues for 9 minutes) ..... I want to amend my earlier statements. I'd like counsel present before I answer anything else.",
        },
      ],
    },
    {
      id: "neha-sharma",
      name: "Neha Sharma",
      role: "Finance Controller",
      location: "Pune — HQ",
      age: 44,
      motive:
        "The internal control that actually fired: she reviewed the revised amount, saw no independent verification of the change, and ordered AP to hold the ₹1.9 lakh balance.",
      tell: "Her hold lasted exactly one day — until Sahil told AP the approval had been 'updated'. She is the reason the second attempt left a cleaner trail, and the best witness in the building.",
      transcript: [
        {
          q: "Ms. Sharma, COM-10: 'Please hold the additional amount until the revised approval is visible.' Why?",
          a: "Because I read the file. A ₹1.9 lakh top-up on PO-2720, one day after creation, justified by 'production scheduling' from the same vendor as September. I asked the one question the process skips: has anyone independently verified this change with the vendor? The answer was no.",
        },
        {
          q: "And then?",
          a: "Then the approval was 'updated' and the payment proceeded — 21 February, 10:04, processed by AP. My hold was satisfied on paper, not on substance. Nobody ever called Nova-Tech. The verification rule exists; I watched it not happen twice.",
        },
        {
          q: "You review financial activity. What did September and February have in common?",
          a: "The same executive, the same vendor, the same move: inflate the quantity after approval, ride it through on a revised document, pay the excess as 'routine'. Revenue rose ₹23 crore; procurement rose ₹24 crore. The difference between this company's growth and its spending is sitting in that pattern.",
        },
      ],
    },
    {
      id: "rohan-malhotra",
      name: "Rohan Malhotra",
      role: "Operations Manager",
      location: "Pune — Plant 2",
      age: 41,
      motive:
        "Owns material requirements. If 400 connector modules and 100 sensor modules were never needed, his requirement sheets are where the lie started — or where it was attributed.",
      tell: "Red herring. The requirement sheets for both inflated POs originated from the vendor side, not operations. He never raised a requirement for the additional quantities at all.",
      transcript: [
        {
          q: "Mr. Malhotra, did operations request the additional 400 PCB connector modules in September?",
          a: "No. Our BOM for the Q4 run was frozen in August — 2,000 modules was the requirement. I first saw 2,400 when the PO extract hit the system. Nobody asked the plant whether we could even stage the extra stock.",
        },
        {
          q: "And the sensor modules in February?",
          a: "Same story. 800 was the plan. The extra 100 appear from nowhere — 'production scheduling' is the phrase in the file, which is odd, because production is me, and I scheduled nothing.",
        },
        {
          q: "So the requirement never came from the floor.",
          a: "Never. Requirements flow ops → procurement in writing. For both Nova-Tech revisions, the paper flows the other way — vendor to procurement exec, backwards. That's not how my department works. That's how someone else's does.",
        },
      ],
    },
  ],
  evidence: [
    {
      id: "ev-nv-case-brief",
      title: "The Case File — Asteron Consumer Electronics",
      kind: "audit-report",
      group: "Case File",
      date: "FY 2025–26",
      source: "Internal investigation mandate — Asteron Consumer Electronics Pvt. Ltd.",
      size: "2 pages",
      excerpt:
        "Procurement rules, company profile, and the financial-impact bands the verdict must use.",
      lines: [
        { t: "kv", k: "COMPANY", v: "Asteron Consumer Electronics Pvt. Ltd." },
        { t: "kv", k: "LOCATION", v: "Pune, Maharashtra" },
        { t: "kv", k: "INDUSTRY", v: "Consumer Electronics Manufacturing" },
        { t: "kv", k: "PERIOD", v: "April 2025 – March 2026" },
        { t: "divider" },
        { t: "p", v: "During FY 2025–26, procurement expenditure increased versus the previous financial year. Revenue also increased. Internal review has flagged transactions and procurement records requiring further examination across financials, employees, vendors, transactions, purchase orders, invoices, communications and audit logs." },
        { t: "hl", v: "PROCUREMENT RULES — judge every record against these" },
        { t: "mono", v: "R1  Purchases above ₹5,00,000      → additional approval" },
        { t: "mono", v: "R2  Purchases above ₹25,00,000     → CFO approval" },
        { t: "mono", v: "R3  Any change to an approved PO   → documented + approved" },
        { t: "mono", v: "R4  Supplier bank-account changes  → independent verification" },
        { t: "mono", v: "R5  Procurement records            → reflect approved requirement" },
        { t: "divider" },
        { t: "hl", v: "FINANCIAL-IMPACT BANDS — classify the suspected loss" },
        { t: "mono", v: "A  ₹0 – ₹5 lakh      B  ₹5 – ₹10 lakh     C  ₹10 – ₹20 lakh" },
        { t: "mono", v: "D  ₹20 – ₹30 lakh    E  ₹30 – ₹50 lakh    F  > ₹50 lakh" },
        { t: "divider" },
        { t: "p", v: "Investigation rule: do not rely on a single record. The answer must be developed by connecting information across the case study and evidence documents." },
        { t: "stamp", v: "INTERNAL — FORENSIC REVIEW UNIT ONLY" },
      ],
    },
    {
      id: "ev-nv-vendor-precision",
      title: "Vendor V001 — Precision Packaging Solutions",
      kind: "vendor-profile",
      group: "Vendors",
      date: "Established 2018",
      source: "Vendor master file — Asteron procurement",
      size: "1 profile",
      excerpt:
        "Long stable relationship, rare PO revisions, no bank changes. The baseline every other vendor is compared against.",
      lines: [
        { t: "kv", k: "VENDOR", v: "V001 — PRECISION PACKAGING SOLUTIONS" },
        { t: "kv", k: "CONTACT", v: "Farah Khan" },
        { t: "kv", k: "LOCATION", v: "Pune" },
        { t: "kv", k: "BUSINESS", v: "Packaging Manufacturer" },
        { t: "kv", k: "BANK", v: "HDFC ••••4821 — unchanged since onboarding" },
        { t: "divider" },
        { t: "mono", v: "SPEND   2022 ₹14.8 Cr · 2023 ₹16.2 Cr · 2024 ₹17.1 Cr" },
        { t: "mono", v: "        2025 ₹18.4 Cr · 2026 ₹19.2 Cr" },
        { t: "divider" },
        { t: "p", v: "Asteron supplier since 2019. Typical order ₹5L–₹12L. PO revisions rare. No bank changes. No significant payment disputes." },
        { t: "stamp", v: "STATUS: ROUTINE" },
      ],
    },
    {
      id: "ev-nv-vendor-novatech",
      title: "Vendor V002 — Nova-Tech Components",
      kind: "vendor-profile",
      group: "Vendors",
      date: "Established 2022",
      source: "Vendor master file — Asteron procurement",
      size: "1 profile",
      excerpt:
        "FY25–26 spend jumped ₹3.8 Cr → ₹6.9 Cr. Two significant PO revisions, both quantity increases, both touching one Asteron employee.",
      lines: [
        { t: "kv", k: "VENDOR", v: "V002 — NOVA-TECH COMPONENTS" },
        { t: "kv", k: "CONTACT", v: "Karan Bhatia" },
        { t: "kv", k: "LOCATION", v: "Pune" },
        { t: "kv", k: "BUSINESS", v: "Electronic Components" },
        { t: "kv", k: "BANK", v: "ICICI ••••6714 — unchanged" },
        { t: "divider" },
        { t: "mono", v: "SPEND   2022 ₹1.9 Cr · 2023 ₹2.3 Cr · 2024 ₹2.8 Cr" },
        { t: "mono", v: "        2025 ₹3.8 Cr · 2026 ₹6.9 Cr  ← FY25–26 spike" },
        { t: "divider" },
        { t: "p", v: "Asteron supplier since 2022. Typical order ₹5L–₹20L. Limited PO revisions before 2025. No bank changes, no formal payment disputes." },
        { t: "hl", v: "Two significant PO revisions during the investigation period. Both involved quantity increases. Communications exist between Karan Bhatia and Sahil Mehta (Procurement Executive)." },
        { t: "stamp", v: "STATUS: REQUIRES INVESTIGATION" },
      ],
    },
    {
      id: "ev-nv-vendor-zenith",
      title: "Vendor V003 — Zenith Advisory Services",
      kind: "vendor-profile",
      group: "Vendors",
      date: "Established 2022",
      source: "Vendor master file — Asteron procurement",
      size: "1 profile",
      excerpt:
        "Stable spend, no significant PO revisions. Permits staged payments under certain POs — explains the split TX payments.",
      lines: [
        { t: "kv", k: "VENDOR", v: "V003 — ZENITH ADVISORY SERVICES" },
        { t: "kv", k: "CONTACT", v: "Amit Sethi" },
        { t: "kv", k: "LOCATION", v: "Mumbai" },
        { t: "kv", k: "BUSINESS", v: "Procurement & Technical Consulting" },
        { t: "kv", k: "BANK", v: "SBI ••••1938 — unchanged" },
        { t: "divider" },
        { t: "mono", v: "SPEND   2022 ₹3.2 Cr · 2023 ₹4.4 Cr · 2024 ₹5.0 Cr" },
        { t: "mono", v: "        2025 ₹5.1 Cr · 2026 ₹5.7 Cr" },
        { t: "divider" },
        { t: "p", v: "Asteron supplier since 2023. Typical order ₹3L–₹9L. No significant PO revisions. Staged payments allowed under certain POs. No bank changes, no major disputes." },
        { t: "stamp", v: "STATUS: ROUTINE / REVIEWED" },
      ],
    },
    {
      id: "ev-nv-vendor-brightline",
      title: "Vendor V004 — Brightline Trading",
      kind: "vendor-profile",
      group: "Vendors",
      date: "Established 2020",
      source: "Vendor master file — Asteron procurement",
      size: "1 profile",
      excerpt:
        "Gradual spend growth, occasional operational PO revisions. High-value orders, clean records.",
      lines: [
        { t: "kv", k: "VENDOR", v: "V004 — BRIGHTLINE TRADING" },
        { t: "kv", k: "CONTACT", v: "Suresh Patil" },
        { t: "kv", k: "LOCATION", v: "Nashik" },
        { t: "kv", k: "BUSINESS", v: "Electrical & Power Components" },
        { t: "kv", k: "BANK", v: "Axis ••••5206 — unchanged" },
        { t: "divider" },
        { t: "mono", v: "SPEND   2022 ₹9.8 Cr · 2023 ₹10.6 Cr · 2024 ₹11.1 Cr" },
        { t: "mono", v: "        2025 ₹11.7 Cr · 2026 ₹12.6 Cr" },
        { t: "divider" },
        { t: "p", v: "Asteron supplier since 2021. Typical order ₹7L–₹20L+. Occasional operational PO revisions. No bank changes, no significant disputes. Spending increased gradually." },
        { t: "stamp", v: "STATUS: ROUTINE" },
      ],
    },
    {
      id: "ev-nv-vendor-comparison",
      title: "Vendor Comparison Matrix",
      kind: "ledger",
      group: "Vendors",
      date: "FY 2025–26",
      source: "Procurement analytics — prepared for internal review",
      size: "1 matrix",
      excerpt:
        "All four vendors side by side. Look for the unusual combination, not the unusual single fact.",
      lines: [
        { t: "mono", v: "VENDOR            EST   REL     FY26      PATTERN  REVISIONS  STAGED  BANK" },
        { t: "mono", v: "Precision Pack.   2018  2019–   ₹19.2 Cr  Stable   Rare       No      No" },
        { t: "mono", v: "Nova-Tech Comp.   2022  2022–   ₹6.9 Cr   Increased 2 SIGNIF.   No      No" },
        { t: "mono", v: "Zenith Advisory   2022  2023–   ₹5.7 Cr   Stable   None sig.  Yes     No" },
        { t: "mono", v: "Brightline Trad.  2020  2021–   ₹12.6 Cr  Stable   Occasional No      No" },
        { t: "divider" },
        { t: "p", v: "Reading the matrix: vendor size and order value are not red flags by themselves. Precision and Brightline move far more money than Nova-Tech with clean histories. The unusual combination is concentrated in one row — growth, revisions, and who communicates with whom." },
        { t: "hl", v: "No vendor shows a bank-account change (Rule R4). Eliminate that line of inquiry and follow the PO revisions." },
        { t: "stamp", v: "COMPARATIVE ANALYSIS — INTERNAL" },
      ],
    },
    {
      id: "ev-nv-financials",
      title: "Company Financial Overview — FY24–25 vs FY25–26",
      kind: "ledger",
      group: "Financials",
      date: "March 2026",
      source: "Asteron finance — management accounts extract",
      size: "2 tables",
      excerpt:
        "Procurement spend grew ₹24.1 Cr while operating profit fell. The gap is the case.",
      lines: [
        { t: "mono", v: "ITEM                 FY 2024–25    FY 2025–26" },
        { t: "mono", v: "Revenue              ₹248.0 Cr     ₹271.5 Cr" },
        { t: "mono", v: "Cost of Materials    ₹128.4 Cr     ₹151.7 Cr" },
        { t: "mono", v: "Operating Expenses   ₹51.6 Cr      ₹55.2 Cr" },
        { t: "mono", v: "Operating Profit     ₹68.0 Cr      ₹64.6 Cr  ← fell" },
        { t: "hl", v: "PROCUREMENT SPEND    ₹119.8 Cr     ₹143.9 Cr  ← +₹24.1 Cr" },
        { t: "divider" },
        { t: "mono", v: "SELECTED VENDOR SPEND      FY24–25    FY25–26" },
        { t: "mono", v: "Precision Packaging        ₹18.4 Cr   ₹19.2 Cr   +₹0.8" },
        { t: "mono", v: "Nova-Tech Components       ₹5.7 Cr    ₹6.9 Cr    +₹1.2 ←" },
        { t: "mono", v: "Zenith Advisory            ₹5.1 Cr    ₹5.7 Cr    +₹0.6" },
        { t: "mono", v: "Brightline Trading         ₹11.7 Cr   ₹12.6 Cr   +₹0.9" },
        { t: "divider" },
        { t: "p", v: "Revenue grew ~9.5%. Cost of materials grew ~18%. Nova-Tech's billing grew ~21% in a single year — on a vendor whose volumes were supposedly stable before 2025. An increase alone is not fraud; find the documents that explain it, or prove that none do." },
        { t: "stamp", v: "MANAGEMENT ACCOUNTS — CONFIDENTIAL" },
      ],
    },
    {
      id: "ev-nv-doc-ab",
      title: "Document Sets A & B — Precision Packaging (clean)",
      kind: "po-invoice",
      group: "Documents",
      date: "Aug 2025 / Jan 2026",
      source: "Procurement records — Precision Packaging Solutions",
      size: "4 documents",
      excerpt:
        "Two full PO→invoice cycles where quantity, price and total agree exactly. Your control sample.",
      lines: [
        { t: "hl", v: "SET A — PO-2417 / INV-PS-8821" },
        { t: "mono", v: "PO-2417   12 Aug 2025   20,000 boxes × ₹48   = ₹9,60,000" },
        { t: "mono", v: "          Approved by: Meera Kapoor" },
        { t: "mono", v: "INV-PS-8821  21 Aug 2025  20,000 boxes × ₹48  = ₹9,60,000" },
        { t: "mono", v: "MATCH: quantity ✓  price ✓  total ✓" },
        { t: "divider" },
        { t: "hl", v: "SET B — PO-2672 / INV-PS-9014" },
        { t: "mono", v: "PO-2672   05 Jan 2026   21,000 boxes × ₹51   = ₹10,71,000" },
        { t: "mono", v: "INV-PS-9014 17 Jan 2026  21,000 boxes × ₹51   = ₹10,71,000" },
        { t: "mono", v: "MATCH: quantity ✓  price ✓  total ✓" },
        { t: "divider" },
        { t: "p", v: "Ledger links: TX-013 (₹9,60,000) and TX-024/TX-025 (₹10,71,000) settle these invoices. Note the duplicate payment entries against PO-2672 in the ledger — verify against the invoice before assuming anything." },
        { t: "stamp", v: "CLEAN THREE-WAY MATCH" },
      ],
    },
    {
      id: "ev-nv-doc-c",
      title: "Document Set C — Nova-Tech PO-2571 → R1",
      kind: "po-invoice",
      group: "Documents",
      date: "15–25 Sep 2025",
      source: "Procurement records — Nova-Tech Components",
      size: "3 documents",
      excerpt:
        "Original PO ₹37,00,000 approved by two officers. One day later the quantity rises 400 units — ₹7,40,000 — and the invoice follows the revision.",
      lines: [
        { t: "hl", v: "ORIGINAL PO-2571 — 15 Sep 2025" },
        { t: "mono", v: "2,000 PCB Connector Modules × ₹1,850 = ₹37,00,000" },
        { t: "mono", v: "Approved by: Meera Kapoor + Arjun Rao (CFO — Rule R2)" },
        { t: "divider" },
        { t: "hl", v: "REVISED PO-2571-R1 — 16 Sep 2025 (one day later)" },
        { t: "mono", v: "2,400 PCB Connector Modules × ₹1,850 = ₹44,40,000" },
        { t: "mono", v: "Change: +400 units · Value added: 400 × ₹1,850 = ₹7,40,000" },
        { t: "mono", v: "Approval: M. Kapoor only — no CFO routing shown" },
        { t: "divider" },
        { t: "hl", v: "INVOICE INV-NT-1048 — 25 Sep 2025" },
        { t: "mono", v: "2,400 units × ₹1,850 = ₹44,40,000 — matches the REVISED PO" },
        { t: "divider" },
        { t: "p", v: "The invoice was raised to the revised quantity, not the approved requirement. Rule R3 requires any PO change to be documented and approved — the revision is approved, but nothing on file documents WHY 400 extra modules were needed. Operations never raised the requirement (see Rohan Malhotra's statement)." },
        { t: "hl", v: "Ledger links: TX-015 ₹37,00,000 (18 Sep) + TX-017 ₹7,40,000 (01 Oct) = ₹44,40,000. The excess was paid as a separate 'routine' line." },
        { t: "stamp", v: "EXCEPTION — QUANTITY CHANGE POST-APPROVAL" },
      ],
    },
    {
      id: "ev-nv-doc-d",
      title: "Document Set D — Nova-Tech PO-2720 → R1",
      kind: "po-invoice",
      group: "Documents",
      date: "09–21 Feb 2026",
      source: "Procurement records — Nova-Tech Components",
      size: "4 documents",
      excerpt:
        "The identical move, five months later: 800 → 900 units, +₹1,90,000, paid as TX-030 after the Finance Controller's hold was talked away.",
      lines: [
        { t: "hl", v: "ORIGINAL PO-2720 — 09 Feb 2026" },
        { t: "mono", v: "800 Sensor Interface Modules × ₹1,900 = ₹15,20,000" },
        { t: "divider" },
        { t: "hl", v: "REVISED PO-2720-R1 — 12 Feb 2026 (three days later)" },
        { t: "mono", v: "900 Sensor Interface Modules × ₹1,900 = ₹17,10,000" },
        { t: "mono", v: "Change: +100 units · Value added: 100 × ₹1,900 = ₹1,90,000" },
        { t: "divider" },
        { t: "hl", v: "INVOICE INV-NT-1167" },
        { t: "mono", v: "900 units × ₹1,900 = ₹17,10,000 — matches the REVISED PO" },
        { t: "divider" },
        { t: "hl", v: "PAYMENTS" },
        { t: "mono", v: "TX-029  19 Feb 2026  ₹15,20,000  (original value)" },
        { t: "mono", v: "TX-030  21 Feb 2026  ₹1,90,000   (the excess — held by Finance, then released)" },
        { t: "divider" },
        { t: "p", v: "Same vendor, same executor, same mechanism as Set C: a small quantity increase immediately after approval, an invoice raised to the inflated number, and the excess settled as its own payment line. The Finance Controller formally asked for the payment to be held pending independent verification (COM-10). It was released one day later on the executive's assurance." },
        { t: "stamp", v: "EXCEPTION — REPEAT PATTERN FLAGGED" },
      ],
    },
    {
      id: "ev-nv-doc-ef",
      title: "Document Sets E & F — Zenith Advisory (staged, clean)",
      kind: "po-invoice",
      group: "Documents",
      date: "Nov 2025 / Mar 2026",
      source: "Procurement records — Zenith Advisory Services",
      size: "4 documents",
      excerpt:
        "Split payments that are exactly legitimate — the counter-example that proves split payments aren't the crime.",
      lines: [
        { t: "hl", v: "SET E — PO-2618  ₹8,40,000 (two instalments permitted)" },
        { t: "mono", v: "TX-020  ₹4,20,000 + TX-021  ₹4,20,000 = ₹8,40,000 ✓" },
        { t: "divider" },
        { t: "hl", v: "SET F — PO-2759  ₹5,90,000" },
        { t: "mono", v: "TX-032  ₹2,95,000 + TX-033  ₹2,95,000 = ₹5,90,000 ✓" },
        { t: "divider" },
        { t: "p", v: "Both staged-payment sequences sum exactly to their authorised PO values, and the POs explicitly permit instalments. Multiple payments are not an irregularity when they match the approved procurement value — compare with Nova-Tech, where the split hides an amount that was never approved at all." },
        { t: "stamp", v: "CLEAN MATCH" },
      ],
    },
    {
      id: "ev-nv-doc-gh",
      title: "Document Sets G & H — Brightline Trading (clean)",
      kind: "po-invoice",
      group: "Documents",
      date: "Jan–Feb 2026",
      source: "Procurement records — Brightline Trading",
      size: "4 documents",
      excerpt:
        "High-value POs with perfect PO/invoice agreement. Big money, clean paper.",
      lines: [
        { t: "hl", v: "SET G — PO-2694" },
        { t: "mono", v: "600 Power Control Boards × ₹18,500 = ₹1,11,00,000" },
        { t: "mono", v: "Invoice matches exactly. TX-026 ₹11,10,000 is one instalment against the larger order." },
        { t: "divider" },
        { t: "hl", v: "SET H — PO-2731" },
        { t: "mono", v: "480 Power Control Boards × ₹18,000 = ₹86,40,000" },
        { t: "mono", v: "Invoice matches exactly. TX-031 ₹8,64,000 settles against it." },
        { t: "divider" },
        { t: "p", v: "Large order values and partial payments are not, by themselves, manipulation. Brightline's paperwork agrees with itself at every step — which is exactly what Nova-Tech's does not." },
        { t: "stamp", v: "CLEAN MATCH" },
      ],
    },
    {
      id: "ev-nv-transactions",
      title: "Transaction Ledger — TX-001 … TX-040",
      kind: "ledger",
      group: "Financials",
      date: "Apr 2025 – Mar 2026",
      source: "Asteron payments system — selected transactions",
      size: "40 entries",
      excerpt:
        "Forty logged payments. Most are routine. Four are not — and two of those are the excess, paid as separate small lines.",
      lines: [
        { t: "mono", v: "ID      DATE         VENDOR              AMOUNT        REF" },
        { t: "mono", v: "TX-001  18 Apr 2025  Precision Pack.     ₹9,60,000     PO-2417" },
        { t: "mono", v: "TX-002  29 Apr 2025  Brightline          ₹7,40,000     routine" },
        { t: "mono", v: "TX-003  06 May 2025  Zenith              ₹4,20,000     routine" },
        { t: "mono", v: "TX-004  15 May 2025  Precision Pack.     ₹8,80,000     routine" },
        { t: "mono", v: "TX-005  24 May 2025  Brightline          ₹6,90,000     routine" },
        { t: "mono", v: "TX-006  03 Jun 2025  Nova-Tech           ₹12,40,000    routine" },
        { t: "mono", v: "TX-007  14 Jun 2025  Zenith              ₹3,80,000     routine" },
        { t: "mono", v: "TX-008  26 Jun 2025  Brightline          ₹8,20,000     routine" },
        { t: "mono", v: "TX-009  05 Jul 2025  Precision Pack.     ₹10,20,000    routine" },
        { t: "mono", v: "TX-010  17 Jul 2025  Nova-Tech           ₹11,80,000    routine" },
        { t: "mono", v: "TX-011  29 Jul 2025  Zenith              ₹4,60,000     routine" },
        { t: "mono", v: "TX-012  08 Aug 2025  Brightline          ₹9,10,000     routine" },
        { t: "mono", v: "TX-013  21 Aug 2025  Precision Pack.     ₹9,60,000     PO-2417" },
        { t: "mono", v: "TX-014  03 Sep 2025  Brightline          ₹7,80,000     routine" },
        { t: "hl", v: "TX-015  18 Sep 2025  Nova-Tech           ₹37,00,000    PO-2571" },
        { t: "mono", v: "TX-016  25 Sep 2025  Zenith              ₹4,10,000     routine" },
        { t: "hl", v: "TX-017  01 Oct 2025  Nova-Tech           ₹7,40,000     routine ←" },
        { t: "mono", v: "TX-018  12 Oct 2025  Brightline          ₹8,60,000     routine" },
        { t: "mono", v: "TX-019  27 Oct 2025  Precision Pack.     ₹8,95,000     routine" },
        { t: "mono", v: "TX-020  14 Nov 2025  Zenith              ₹4,20,000     PO-2618" },
        { t: "mono", v: "TX-021  28 Nov 2025  Zenith              ₹4,20,000     PO-2618" },
        { t: "mono", v: "TX-022  09 Dec 2025  Brightline          ₹9,30,000     routine" },
        { t: "mono", v: "TX-023  18 Dec 2025  Nova-Tech           ₹13,20,000    routine" },
        { t: "mono", v: "TX-024  05 Jan 2026  Precision Pack.     ₹10,71,000    PO-2672" },
        { t: "mono", v: "TX-025  17 Jan 2026  Precision Pack.     ₹10,71,000    PO-2672" },
        { t: "mono", v: "TX-026  20 Jan 2026  Brightline          ₹11,10,000    PO-2694" },
        { t: "mono", v: "TX-027  29 Jan 2026  Nova-Tech           ₹6,80,000     routine" },
        { t: "mono", v: "TX-028  05 Feb 2026  Zenith              ₹4,70,000     routine" },
        { t: "hl", v: "TX-029  19 Feb 2026  Nova-Tech           ₹15,20,000    PO-2720" },
        { t: "hl", v: "TX-030  21 Feb 2026  Nova-Tech           ₹1,90,000     PO-2720 ←" },
        { t: "mono", v: "TX-031  27 Feb 2026  Brightline          ₹8,64,000     PO-2731" },
        { t: "mono", v: "TX-032  07 Mar 2026  Zenith              ₹2,95,000     PO-2759" },
        { t: "mono", v: "TX-033  18 Mar 2026  Zenith              ₹2,95,000     PO-2759" },
        { t: "mono", v: "TX-034  20 Mar 2026  Nova-Tech           ₹9,20,000     routine" },
        { t: "mono", v: "TX-035  22 Mar 2026  Precision Pack.     ₹8,40,000     routine" },
        { t: "mono", v: "TX-036  24 Mar 2026  Brightline          ₹7,95,000     routine" },
        { t: "mono", v: "TX-037  26 Mar 2026  Nova-Tech           ₹5,60,000     routine" },
        { t: "mono", v: "TX-038  27 Mar 2026  Precision Pack.     ₹8,10,000     routine" },
        { t: "mono", v: "TX-039  28 Mar 2026  Brightline          ₹8,25,000     routine" },
        { t: "mono", v: "TX-040  30 Mar 2026  Nova-Tech           ₹4,80,000     routine" },
        { t: "divider" },
        { t: "p", v: "Note: selected payments — not the complete history of any vendor. A routine label is a classification, not a clearance: TX-017 and TX-030 are booked 'routine' but trace directly to the two revised POs." },
        { t: "stamp", v: "PAYMENTS SYSTEM EXTRACT" },
      ],
    },
    {
      id: "ev-nv-comms-1",
      title: "Communications File I — September 2025 (COM-01…06)",
      kind: "comm-log",
      group: "Communications",
      date: "10–17 Sep 2025",
      source: "Email capture — preserved for internal investigation",
      size: "6 messages",
      excerpt:
        "The vendor's quantity sheet goes straight to the procurement executive. AP spots the mismatch the same day the invoice is queried.",
      lines: [
        { t: "hl", v: "COM-01 · 10 Sep · Sahil Mehta → Karan Bhatia (Nova-Tech)" },
        { t: "p", v: "“Please send the updated component requirement sheet before the PO is finalised.”" },
        { t: "hl", v: "COM-02 · 11 Sep · Karan Bhatia → Sahil Mehta" },
        { t: "p", v: "“Attached the revised quantity sheet. Please confirm once updated.”" },
        { t: "hl", v: "COM-03 · 15 Sep · Sahil Mehta → Meera Kapoor" },
        { t: "p", v: "“Nova-Tech has confirmed availability for the additional quantity. I have updated the requirement in the system for your review.”" },
        { t: "hl", v: "COM-04 · 16 Sep · Karan Bhatia → Sahil Mehta" },
        { t: "p", v: "“The additional quantity is confirmed from our side. Please update the order accordingly.”" },
        { t: "hl", v: "COM-05 · 17 Sep · Vikram Joshi → Sahil Mehta" },
        { t: "p", v: "“The invoice amount is higher than the original PO value. Please confirm the revised approval reference.”" },
        { t: "hl", v: "COM-06 · 17 Sep · Sahil Mehta → Vikram Joshi" },
        { t: "p", v: "“The quantity was revised after confirmation of additional requirement. The updated approval is available in the system.”" },
        { t: "divider" },
        { t: "p", v: "Read against the audit log: the 'requirement' originates from the VENDOR (COM-01/02), the system update is performed by Sahil himself (COM-03, AL-004), and when AP queries the invoice, the answer points back to the same system the same man edits. The chain never touches an independent verifier." },
        { t: "stamp", v: "PRESERVED — FORENSIC MAILBOX CAPTURE" },
      ],
    },
    {
      id: "ev-nv-comms-2",
      title: "Communications File II — February 2026 (COM-07…12)",
      kind: "comm-log",
      group: "Communications",
      date: "06–15 Feb 2026",
      source: "Email capture — preserved for internal investigation",
      size: "6 messages",
      excerpt:
        "The pattern repeats — including Finance's hold, and the assurance that dissolved it.",
      lines: [
        { t: "hl", v: "COM-07 · 06 Feb · Karan Bhatia → Sahil Mehta" },
        { t: "p", v: "“We can accommodate the additional modules. Let me know once the order quantity has been updated.”" },
        { t: "hl", v: "COM-08 · 10 Feb · Sahil Mehta → Karan Bhatia" },
        { t: "p", v: "“Working on it. I will confirm once the revised order is reflected.”" },
        { t: "hl", v: "COM-09 · 12 Feb · Sahil Mehta → Meera Kapoor" },
        { t: "p", v: "“Nova-Tech has requested a small quantity adjustment due to production scheduling. Revised PO is ready for review.”" },
        { t: "hl", v: "COM-10 · 13 Feb · Neha Sharma → Vikram Joshi" },
        { t: "p", v: "“Please hold the additional amount until the revised approval is visible.”" },
        { t: "hl", v: "COM-11 · 14 Feb · Sahil Mehta → Vikram Joshi" },
        { t: "p", v: "“The revised approval has been updated. You may proceed with the balance.”" },
        { t: "hl", v: "COM-12 · 15 Feb · Karan Bhatia → Sahil Mehta" },
        { t: "p", v: "“Thanks. We will keep the invoice aligned with the revised quantity.”" },
        { t: "divider" },
        { t: "p", v: "COM-12 is the vendor confirming — in writing — that their invoice will be made to match whatever quantity is entered on the Asteron side. COM-10 vs COM-11 is the control failing in real time: Finance's hold is lifted by the same executive under review, and the balance pays the next morning (TX-030, 21 Feb)." },
        { t: "stamp", v: "PRESERVED — FORENSIC MAILBOX CAPTURE" },
      ],
    },
    {
      id: "ev-nv-audit-log",
      title: "System Audit Log — AL-001 … AL-015",
      kind: "audit-report",
      group: "Audit Trail",
      date: "Sep 2025 – Feb 2026",
      source: "Procurement system — immutable action log",
      size: "15 entries",
      excerpt:
        "Who did what, and when. Every creation, every change, every approval — keyed by user ID. Map the IDs to the personnel file.",
      lines: [
        { t: "mono", v: "ID      DATE         TIME   USER   ACTION" },
        { t: "mono", v: "AL-001  10 Sep 2025  10:14  SM029  Opened vendor V002" },
        { t: "mono", v: "AL-002  11 Sep 2025  16:42  SM029  Uploaded requirement file for V002" },
        { t: "hl", v: "AL-003  15 Sep 2025  09:18  SM029  Created PO-2571" },
        { t: "hl", v: "AL-004  16 Sep 2025  11:07  SM029  Changed PO-2571 quantity: 2,000 → 2,400" },
        { t: "hl", v: "AL-005  16 Sep 2025  11:11  SM029  Submitted revised PO" },
        { t: "mono", v: "AL-006  16 Sep 2025  14:36  MK014  Approved revised PO" },
        { t: "mono", v: "AL-007  25 Sep 2025  15:22  SM029  Uploaded invoice INV-NT-1048" },
        { t: "mono", v: "AL-008  17 Sep 2025  09:05  VJ018  Reviewed payment TX-015" },
        { t: "divider" },
        { t: "mono", v: "AL-009  06 Feb 2026  13:26  SM029  Opened PO-2720" },
        { t: "mono", v: "AL-010  10 Feb 2026  17:41  SM029  Edited quantity" },
        { t: "hl", v: "AL-011  12 Feb 2026  10:52  SM029  Changed quantity: 800 → 900" },
        { t: "mono", v: "AL-012  12 Feb 2026  10:56  SM029  Submitted revised PO" },
        { t: "mono", v: "AL-013  13 Feb 2026  12:20  NS021  Reviewed revised amount" },
        { t: "mono", v: "AL-014  19 Feb 2026  14:18  VJ018  Processed TX-029" },
        { t: "mono", v: "AL-015  21 Feb 2026  10:04  VJ018  Processed TX-030" },
        { t: "divider" },
        { t: "hl", v: "USER ID KEY — map to the personnel file" },
        { t: "mono", v: "SM029 = Sahil Mehta (Procurement Executive)   MK014 = Meera Kapoor" },
        { t: "mono", v: "VJ018 = Vikram Joshi (AP Manager)             NS021 = Neha Sharma" },
        { t: "divider" },
        { t: "p", v: "The sequences that matter: AL-003 → AL-004 → AL-005 (created, then self-revised within 25 hours) and AL-009 → AL-010 → AL-011 → AL-012 (the identical cycle in February). The same user who created each PO also changed its quantity, submitted the revision, and uploaded the vendor's invoice (AL-007). Approvals exist — but no entry shows any independent verification of the changes required by Rule R3." },
        { t: "stamp", v: "IMMUTABLE LOG — DO NOT EDIT" },
      ],
    },
  ],
  hints: [
    {
      id: "nv-hint-1",
      cost: 250,
      text: "Match each Nova-Tech invoice against its ORIGINAL purchase order, not the revised one. INV-NT-1048 bills 2,400 units against a PO approved for 2,000; INV-NT-1167 bills 900 against 800. Then find who paid the difference — TX-017 and TX-030 are booked as 'routine'.",
    },
    {
      id: "nv-hint-2",
      cost: 250,
      text: "The audit log is the backbone. SM029 created PO-2571, changed its quantity, submitted the revision, and uploaded the vendor's invoice — then repeated the identical cycle on PO-2720. Map SM029 to the personnel directory, and read COM-02/COM-04: the 'requirement' comes from the vendor contact, Karan Bhatia, not from operations.",
    },
    {
      id: "nv-hint-3",
      cost: 250,
      text: "Do the arithmetic: (400 × ₹1,850) + (100 × ₹1,900) = ₹7,40,000 + ₹1,90,000 = ₹9,30,000. That is the inflated value — which lands in impact band B (₹5–10 lakh), not a bigger one. Bigger numbers appear in the file; they are not the answer.",
    },
  ],
  solution: {
    headline:
      "Sahil Mehta inflated approved Nova-Tech purchase orders after sign-off — +400 units on PO-2571 and +100 on PO-2720 — coordinated with vendor contact Karan Bhatia, and paid ₹9,30,000 of unapproved value out as 'routine' payments.",
    points: [
      "The mechanism: PO-2571 was approved at 2,000 units (₹37,00,000) with CFO sign-off. One day later, audit log AL-004 shows SM029 — Sahil Mehta — personally changing the quantity to 2,400 (₹44,40,000). The vendor's invoice INV-NT-1048 was raised to the inflated number and uploaded by Mehta himself (AL-007). The ₹7,40,000 difference was paid as TX-017, booked 'routine'.",
      "The repeat: in February the identical cycle runs on PO-2720 — created at 800 units (₹15,20,000), revised to 900 (₹17,10,000) by the same user ID, invoice matched to the revision, and the ₹1,90,000 excess paid as TX-030 after the Finance Controller's formal hold was lifted on Mehta's assurance that the approval was 'in the system'.",
      "The coordination: the quantity sheets originate from Nova-Tech's Karan Bhatia directly to Mehta (COM-01/02/04/07/12) — including COM-12, where the vendor confirms the invoice will be 'aligned with the revised quantity'. Operations never requested the additional units; the requirement was manufactured on the vendor side.",
      "The controls that failed: Rule R3 (documented, approved changes) was satisfied on paper but verified by no one independent; Rule R2 routing was dodged because the excess was paid as separate routine lines; and the approval chain (Meera Kapoor) relied entirely on the file the executor maintained.",
      "The number: total unapproved value paid = ₹7,40,000 + ₹1,90,000 = ₹9,30,000 — impact band B (₹5–10 lakh). No bank-account changes occurred anywhere in the file (Rule R4 is clean); the irregularity is quantity inflation, not account diversion.",
    ],
  },
  culpritName: "Sahil Mehta",
  keyExhibitIds: ["ev-nv-doc-c", "ev-nv-doc-d", "ev-nv-audit-log"],
  verdict: {
    vendor: {
      label: "Which vendor is connected to the suspected activity?",
      placeholder: "Select the vendor at the centre of the pattern",
      options: [
        { id: "v001", label: "V001 — Precision Packaging Solutions" },
        { id: "v002", label: "V002 — Nova-Tech Components" },
        { id: "v003", label: "V003 — Zenith Advisory Services" },
        { id: "v004", label: "V004 — Brightline Trading" },
      ],
      answerId: "v002",
    },
    impact: {
      label: "Financial impact — which band covers the inflated value?",
      placeholder: "Compute it: ΔQty × unit price on both revised POs",
      options: [
        { id: "a", label: "A — ₹0–₹5 lakh" },
        { id: "b", label: "B — ₹5–₹10 lakh" },
        { id: "c", label: "C — ₹10–₹20 lakh" },
        { id: "d", label: "D — ₹20–₹30 lakh" },
        { id: "e", label: "E — ₹30–₹50 lakh" },
        { id: "f", label: "F — >₹50 lakh" },
      ],
      answerId: "b",
    },
  },
  /* Free discovery until the full chain is authored for this case. */
  unlocks: {
    "ev-nv-doc-c": { type: "free" },
    "ev-nv-doc-d": { type: "free" },
    "ev-nv-audit-log": { type: "free" },
  },
  clues: [],
  hotspots: [],
  puzzle: {
    prompt:
      "Chain — to be authored: enter the checkpoint value recorded in the audit log.",
    answer: "0",
    toleranceHint: "Placeholder — replace when the Nova-Tech discovery chain is authored.",
  },
};
